[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[phases.build]
cmds = ["bun run build"]
cacheDirectories = [".next/cache"]

[start]
cmd = "bun run start"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"
