[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]
cacheDirectories = ["node_modules/.cache"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = [".next/cache"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"
